apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: "my-test-bucket-2"
  description: Cloud Storage Bucket
  tags:
    - gcp
    - gcs-bucket
spec:
  type: gcs-bucket
  owner: team-A
  lifecycle: experimental
